### ISSUE TITLE
Storing of the Raylib Textures

### ISSUE THREAD

**Issue by klemmse** [Epitech-R-Type/R-Type#29]
The Idea is that we don't store the textures in the components, instead we store a vector<vector<Texture>>, which means we have a vector for each animation stored in a vector. This means we would have all sprites in the memory even if we don't need them, but we would only need to store it once no matter how many entities need it. My Idea was to make this vector global, so that we can access it through an index stored in the component. That would, however, not be very clean. So Nicolas said we should instead store it in the manager and access it through smart pointers. If I understand this correctly, this means we would store the pointer in the component, but that would make the serialization a lot harder.

So please answer in a comment what you think about this.

**Comment by nLatt** [comment]
tbf I don't think this is necessary, they are already all loaded into memory because of our binary, the component should just contain file number, x & y, length and width. The system reponsible for drawing will grab the images. wdyt @mindoodoo

**Comment by mindoodoo** [comment]
Yeah in the long run it most likely be done differently because of the asset compilation in the binary.

However, in the meantime (as I doubt we will get to it before monday or tuesday), it's crucial to find a system to work with for the time being. I am definitely not a fan of the global vector either.

A system I would maybe recommend is creating an asset manager class, that would be used to load up the sprite sheet. Ideally, every frame for each animation is stored in correct order in the sprite sheet so that we only need to specify the starting frame id, and the frame count for each animation. (Note: you could also add a frame temporality integer stating how long the animation takes to run one iteration).
We would then use this asset manager to query the frame we need to display at a given time. This can be done in the logic of the component, however beware I am currently working on a full overhaul of the ECS that will eliminate all logic from the components.

The idea behind the ECS refactor will be that you will have a system (ie: a standalone function), that will then query the entity manager for all entities that have the sprite component. Once all these entities are aquired, you will then be able to retrieve the animation metadata in order to display the given frame that you want to display.
The main idea behind this quick explanation, is that you should have the heavy lifting be done by an external class, as with the new ECS you won't be able to implement methods directly on the components.

Does that make sens @klemmse ? You can keep an eye on #28

**Comment by mindoodoo** [comment]
> Systems are just functions. You provide them with the scene, and they can “view” a section of the scene with a SceneView, providing what components they’re interested in. You then do whatever processing the system needs to do.

I am currently implementing something pretty similar to [this](https://www.david-colson.com/2020/02/09/making-a-simple-ecs.html)
